# Generated by Django 5.0.7 on 2024-08-05 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picksA', models.CharField(max_length=255)),
                ('picksB', models.CharField(max_length=255)),
                ('rankingA', models.FloatField()),
                ('rankingB', models.FloatField()),
                ('trade_from', models.CharField(max_length=255)),
                ('trade_to', models.CharField(max_length=255)),
                ('calculation', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
